### ISSUE TITLE
gnsync return 'Sorry, operation has failed!!!.' after few seconds

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#31] opened 2016-01-30 19:48 UTC
`gnsync --path ~/.local/share/notes/Notes --logpath ~/.local/share/notes/gnsync.log --two-way`

**Comment by jeffkowalski** [comment] 2016-08-15 01:53
duplicate of #21

**Closed by jeffkowalski** 2016-08-15 01:53 UTC
